default: &default
  adapter: sqlite3
  encoding: utf8

development:
  <<: *default
  database: db/rubyjobs_development.sqlite3

test:
  <<: *default
  database: db/rubyjobs_test.sqlite3

production:
  adapter: postgresql
  encoding: utf8
  database: rubyjobs_production
  username: root
  password:
